GET localhost:8081/api/v1/articles/get/17
Authorization: test1
###
GET localhost:8081/api/v1/articles/all
Authorization: test1
###
POST localhost:8081/api/v1/articles/create
Accept: application/json
Content-Type: application/json
Authorization: test1

{
  "title": "new Title",
  "date": "2023-03-31",
  "annotation": "Аннотация 666",
  "body": "Текст статьи 666",
  "counter": "123"
}
###
DELETE localhost:8081/api/v1/articles/delete/7
Authorization: test1
###
PUT localhost:8081/api/v1/articles/update/1
Authorization: test1
Accept: application/json
Content-Type: application/json

{
  "title": "2021-03-31"
}

